---
# 定义工作负载
apiVersion: apps/v1
kind: Deployment  # 无状态部署
metadata:
  name: springboot-app
  namespace: my-project   # TODO 命名空间
  labels:
    app: springboot-app
spec:
  replicas: 3 # TODO 3个副本
  strategy:
    rollingUpdate: # 由于replicas为3,则整个升级,pod个数在2-4个之间
      maxSurge: 1        # 滚动升级时会先启动1个pod
      maxUnavailable: 1  # 滚动升级时允许的最大Unavailable的pod个数
  selector:
    matchLabels:
      app: springboot-app
  template:
    metadata:
      labels:
        app: springboot-app
    spec:
      imagePullSecrets:
        - name: aliyun-docker-registry-auth  # TODO 提前在项目下配置访问阿里云仓库的账号密码
      containers:
        - name: springboot-app
          image: registry.cn-hangzhou.aliyuncs.com/zhengqingya/springboot-demo # TODO 镜像地址
          imagePullPolicy: Always
          env: # 环境变量
            - name: JAVA_OPTS
              value: -XX:+UseG1GC -Xms100m -Xmx100m -Dserver.port=8080
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          # CPU内存限制
          resources:
            limits:
              cpu: 300m
              memory: 600Mi
          # 就绪探针 -- 如果准备就绪探针未返回200,则不会向其发送流量
          readinessProbe:
            initialDelaySeconds: 10 # 容器启动后要等待多少秒后存活和就绪探测器才被初始化，默认是0秒，最小值是0。
            periodSeconds: 10 # 执行探测的时间间隔（单位是秒）。默认是10秒。最小值是1。
            timeoutSeconds: 5 # 探测的超时后等待多少秒。默认值是1秒。最小值是1。
            failureThreshold: 3 # 当 Pod 启动了并且探测到失败，Kubernetes 的重试次数。存活探测情况下的放弃就意味着重新启动容器。就绪探测情况下的放弃 Pod 会被打上未就绪的标签。默认值是3。最小值是1。
            httpGet:
              scheme: HTTP
              port: 8080
              path: /api/time
          # 存活探针 -- 如果存活探针未返回200,则会重启Pod
          livenessProbe:
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
            httpGet:
              scheme: HTTP
              port: 8080
              path: /api/time

---
# 定义服务
apiVersion: v1
kind: Service
metadata:
  name: springboot-app  # TODO 服务名
  namespace: my-project   # TODO 命名空间
spec:
  selector:
    app: springboot-app # TODO  label selector配置，将选择具有label标签的Pod作为管理
  type: NodePort # 访问方式  ClusterIP/NodePort
  ports:
    - name: http            # 端口名称
      port: 8080
      protocol: TCP    # 端口协议，支持TCP和UDP，默认TCP
      targetPort: 8080
      nodePort: 666  # TODO 当`type = NodePort`时 对外开放端口
  sessionAffinity: None  # 是否支持session